SDK714: update for wl exe (missing with 2018 --> 2022 update)
Note: small addendum for commit https://bitbucket.org/pedro311/freshtomato-arm/commits/a8b563c74f9837ec0d5d4e509082f562140064df

fix for:
ERROR: unknown driver station info version 5